### ISSUE TITLE
`Headline` alignment `right` seems to have broken behaviour

### ISSUE THREAD

**Issue by julrich** [kickstartDS/kickstartDS#1235]
See: ![grafik](https://user-images.githubusercontent.com/136760/207700410-d0c09614-fc35-43cd-9355-9b62c6c04a7a.png)

That doesn't look like `right`.

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@3.0.0-next.4`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0-next.4), [`@kickstartds/blog@3.0.0-next.3`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0-next.3), [`@kickstartds/core@3.0.0-next.3`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0-next.3), [`@kickstartds/form@3.0.0-next.3`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0-next.3) :rocket:

**Comment by lmestel** [comment]
:rocket: Issue was released in  :rocket:
