### ISSUE TITLE
Create UX concept for MVP token playground

### ISSUE THREAD

**Issue by julrich** [kickstartDS/kickstartDS#1247]
Should focus on our branding token set: https://www.kickstartds.com/docs/foundations/token/branding-token

**Comment by DanielLeyUX** [comment]
High level design of app has been concepted and roughly layouted. 

Figma comp: https://www.figma.com/file/ONTKSPHZJ6LAqHW7ui55HN/ksDS_CD?node-id=1837%3A5813&t=G1BkVb7zHijn21ha-1

**Next steps:**

* switch to layout dev-mode
* decide on how to design configuration of each branding token category (e.g. colors, typo, etc.)
* layout preview aside of token categories 
* refine layout of page preview
