### ISSUE TITLE
Evaluate technical considerations for token playground

### ISSUE THREAD

**Issue by julrich** [kickstartDS/kickstartDS#1248]
We want to validate that running Style Dictionary, and thus our token generation pipeline, in the browser. This should serve as input to make an informed decision on if and when this could be implemented.

**Comment by DanielLeyUX** [comment]
We have checked and decided on how to implement the Token Playground. A first version of a clickable prototype was developed and even iterated already. 

Proto URL: https://mellow-alfajores-55113e.netlify.app/

**Decisions:**

* use Radix as application UI library 
* continue to use web worker to decouple UI and processing of token
