### ISSUE TITLE
Improve component types

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1269]
![grafik](https://user-images.githubusercontent.com/31414552/226609748-ec6e8595-a7e1-4bd3-8d60-b5565c3971b2.png)

Narrow componten prop types to get propper types for `onClick` handler etc.

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@2.0.4-next.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%402.0.4-next.2), [`@kickstartds/blog@2.0.4-next.3`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%402.0.4-next.3), [`@kickstartds/form@2.0.4-next.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%402.0.4-next.2) :rocket:
