### ISSUE TITLE
Animate collapsible boxes with CSS

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1311]
We can simplify the collapsible box by replacing most of the JS with CSS.

https://keithjgrant.com/posts/2023/04/transitioning-to-height-auto/

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0-beta.0), [`@kickstartds/blog@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0-beta.0), [`@kickstartds/bundler@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%403.0.0-beta.0), [`@kickstartds/core@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0-beta.0), [`@kickstartds/form@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0-beta.0) :rocket:

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0-beta.0), [`@kickstartds/blog@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0-beta.0), [`@kickstartds/bundler@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%403.0.0-beta.0), [`@kickstartds/core@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0-beta.0), [`@kickstartds/form@3.0.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0-beta.0) :rocket:

**Comment by lmestel** [comment]
:rocket: Issue was released in  :rocket:

**Comment by lmestel** [comment]
:rocket: Issue was released in  :rocket:
