### ISSUE TITLE
Section content- & headline alignment

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1478]
New Section Props:

- `contentWidth`: `unset` (default), `narrow`, `default`, `wide`
- `contentAlign`: `left`, `center` (default), `right`
- `headlineWidth`: `unset` (default), `narrow`, `default`, `wide`
- `headlineAlign`: `left`, `center` (default), `right`

Headline modifications:

- remove the `max-width` style
- fix `align: "right"` see https://github.com/kickstartDS/kickstartDS/issues/1235

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@3.0.0-next.4`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0-next.4), [`@kickstartds/blog@3.0.0-next.3`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0-next.3), [`@kickstartds/core@3.0.0-next.3`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%403.0.0-next.3), [`@kickstartds/form@3.0.0-next.3`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0-next.3) :rocket:

**Comment by lmestel** [comment]
:rocket: Issue was released in  :rocket:
