### ISSUE TITLE
Add Button Group to Section

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1524]
New Prop `buttons` same as #1525

Button Group width is same as `content.width`

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@3.0.0-next.11`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0-next.11), [`@kickstartds/blog@3.0.0-next.10`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0-next.10), [`@kickstartds/form@3.0.0-next.10`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0-next.10) :rocket:

**Comment by lmestel** [comment]
:rocket: Issue was released in  :rocket:
