### ISSUE TITLE
Button Group Component

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1525]
Props:

- `align`: left (default), center, right, space-between, grow
- `buttons`: Array of Button Props

Component Tokens:

- button-min-width (default unset)
- gutter-v (default: stack-m)
- gutter-h (default: inline-s)

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@3.0.0-next.9`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%403.0.0-next.9), [`@kickstartds/blog@3.0.0-next.8`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%403.0.0-next.8), [`@kickstartds/form@3.0.0-next.8`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%403.0.0-next.8) :rocket:

**Comment by lmestel** [comment]
:rocket: Issue was released in  :rocket:
