### ISSUE TITLE
Branding Token: background-color.accent shouldn't be transparent by default

### ISSUE THREAD

**Issue by fleven-kds** [kickstartDS/kickstartDS#1534]
If `background-color.accent` & `background-color.accent-inverted` have a low transparency, a bright coloured font wont be visible because of the white browser background.

**Comment by fleven-kds** [comment]
The `init-tokens` command currently sets it to `ks.color.fg.alpha.8.base` by default. Perhaps we should simply change it to `ks.color.fg.to-bg.8.base`

**Comment by lmestel** [comment]
This was changed in https://github.com/kickstartDS/kickstartDS/commit/ce9bc6e9a59f221efe0fcc97afe2274cc3332e73
