### ISSUE TITLE
Add `file` to `TextField`s `type` prop

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1545]
Error Message: 
`Type '"file"' is not assignable to type '"number" | "text" | "search" | "time" | "tel" | "url" | "email" | "date" | "datetime-local" | "month" | "password" | "week" | undefined'.`

While `file` is valid value in the `type` attribute of an input field, we shoud add it to the types.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/form@4.0.3-next.1`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.3-next.1) :rocket:

**Comment by lmestel** [comment]
:rocket: Issue was released in  :rocket:
