### ISSUE TITLE
Section: add Prop `tileWidth`

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1580]
Possible Values:
* `smallest`, `default`, `medium`, `large`, `largest`

`default` should be the default value set.

Relation to token values to use for those property options, see @fleven-kds comment below.

**Comment by fleven-kds** [comment]
I suggest the same integration as seen here:

https://github.com/kickstartDS/ds-agency/blob/4537574fd9d5d7d7158a81de516ea2f668d73973/src/components/section/section.scss#L20C2-L49C1

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@2.3.0-beta.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%402.3.0-beta.2), [`@kickstartds/blog@2.3.0-beta.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%402.3.0-beta.2), [`@kickstartds/core@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%402.3.0-beta.0), [`@kickstartds/form@2.3.0-beta.2`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%402.3.0-beta.2), [`@kickstartds/style-dictionary@2.3.0-beta.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/style-dictionary%402.3.0-beta.0) :rocket:

**Comment by lmestel** [comment]
:rocket: Issue was released in  :rocket:
