### ISSUE TITLE
Remove focus-visible polyfill

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1682]
`:focus-visible` is now [widely supported](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#browser_compatibility).

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.0.6-next.0), [`@kickstartds/blog@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.0.6-next.0), [`@kickstartds/bundler@4.0.5-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%404.0.5-next.0), [`@kickstartds/core@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%404.0.6-next.0), [`@kickstartds/form@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.6-next.0) :rocket:
