### ISSUE TITLE
Remove SVG fixer

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1699]
The href-fix for inline svgs is no longer needed since firefox 55: https://bugzilla.mozilla.org/show_bug.cgi?id=1357432

We can simply remove `packages/components/base/source/helpers/svg-icon-baseurl.js`.

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.0.6-next.0), [`@kickstartds/blog@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.0.6-next.0), [`@kickstartds/bundler@4.0.5-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%404.0.5-next.0), [`@kickstartds/core@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%404.0.6-next.0), [`@kickstartds/form@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.6-next.0) :rocket:

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.0.6-next.0), [`@kickstartds/blog@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.0.6-next.0), [`@kickstartds/bundler@4.0.5-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/bundler%404.0.5-next.0), [`@kickstartds/core@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/core%404.0.6-next.0), [`@kickstartds/form@4.0.6-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.0.6-next.0) :rocket:
