### ISSUE TITLE
Use `section` tag name for Section Component

### ISSUE THREAD

**Issue by lmestel** [kickstartDS/kickstartDS#1703]

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@4.1.0-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.1.0-next.0), [`@kickstartds/blog@4.1.0-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.1.0-next.0), [`@kickstartds/form@4.1.0-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.1.0-next.0) :rocket:

**Comment by julrich** [comment]
:rocket: Issue was released in [`@kickstartds/base@4.1.0-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/base%404.1.0-next.0), [`@kickstartds/blog@4.1.0-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/blog%404.1.0-next.0), [`@kickstartds/form@4.1.0-next.0`](https://github.com/kickstartDS/kickstartDS/releases/tag/%40kickstartds/form%404.1.0-next.0) :rocket:
