### ISSUE TITLE
Increase large screen support

### ISSUE THREAD

**Issue by fleven-kds** [kickstartDS/kickstartDS#1707]
A key issue on larger devices is that components with built-in background images cannot span the entire screen while fitting within the global layout.

To address this, we plan to add background image support to the section. This will enhance the display on large screen devices by separating the background image functionality from the component, allowing for more flexible component layouts while maintaining a large background image.

**Comment by julrich** [comment]
I'd say we do need extra breakpoints, and section widths should indeed also increase alongside increasing font sizing and general spacing!
