### ISSUE TITLE
Visual - add box background setting

### ISSUE THREAD

**Issue by sstehle** [kickstartDS/kickstartDS#89]
Currently there are three variations of the box.background:

- default
- light
- transparent

My suggestion ist to add a fourth variation to cover all possibilities of background-image, background-color, box-color, text-color combinations.
Also I would suggest to change the title "deflaut" to a predictable title like, for example, "dark"

- dark
- light
- transparent dark (or "transparent dark text") 
- transparent light (or "transparent light text")

**Comment by julrich** [comment]
This had a major overhaul, those problems should be solved now. If not, please open the issue again.
